name: 'UiPath Deploy'
description: 'Deploys .nupkg packages in the Github workspace directory to UiPath Orchestrator'

inputs:
  packagesPath:
    description: 'Relative path to a folder containing the .nupkg to be deployed'
    required: true
  orchestratorUrl: 
    description: 'Orchestrator instance URL'
    required: false
    default: 'https://cloud.uipath.com/'
  orchestratorTenant:
    description: 'Tenant on the Orchestrator instance'
    required: true
  orchestratorFolder:
    description: 'Folder path in modern folder setup'
    required: true
  orchestratorApplicationId:
    description: 'Account for authenticating to Orchestrator'
    required: true
  orchestratorApplicationSecret:
    description: 'Password for the Orchestrator account'
    required: true
  orchestratorApplicationScope:
    description: 'Access scope for external application'
    required: false
    default: "OR.Assets OR.BackgroundTasks OR.Execution OR.Folders OR.Jobs OR.Machines.Read OR.Monitoring OR.Robots.Read OR.Settings.Read OR.TestSets OR.TestSetExecutions OR.TestSetSchedules OR.Users.Read"
  orchestratorLogicalName:
    description: 'Logical name for Orchestrator organization'
    required: true

runs:
  using: "composite"
  steps:    
    - name: UiPath Deploy
      shell: pwsh
      run: | 
        uipcli package deploy "${{ inputs.packagesPath }}" `
          "${{ inputs.orchestratorUrl }}" `
          "${{ inputs.orchestratorTenant }}" `
          --accountForApp "${{ inputs.orchestratorLogicalName }}" `
          --applicationId "${{ inputs.orchestratorApplicationId }}" `
          --applicationSecret "${{ inputs.orchestratorApplicationSecret }}" `
          --applicationScope "${{ inputs.orchestratorApplicationScope }}" `
          --organizationUnit "${{ inputs.orchestratorFolder }}"
          