name: 'UiPath Deploy'
description: 'Deploys .nupkg packages in a given directory to UiPath Orchestrator'

inputs:
  orchestratorUrl:
    description: 'URL to Orchestrator instance'
    required: true
  orchestratorFolderPath:
    description: 'The folder path where the process is deployed'
    required: true
  orchestratorTenant: 
    description: 'Name of the Orchestrator Tenant'
    required: true

secrets:
  orchestratorUsername:
    required: false
  orchestratorPassword:
    required: false
  orchestratorApiKey:
    required: false

runs:
  using: "composite"
  steps:
    - run: package deploy ${{ github.workspace }} "${{ inputs.orchestratorUrl }}" default -t ${{ secrets.orchestratorApiKey }} -a myAccount
      shell: pwsh
