name: 'UiPath Deploy'
description: 'Deploys .nupkg packages in a given directory to UiPath Orchestrator'

inputs:
  orchestratorUrl:
    description: 'URL to Orchestrator instance'
    required: true
  orchestratorFolderPath:
    description: 'The folder path where the process is deployed'
    required: true
  orchestratorTenant: 
    description: 'Name of the Orchestrator Tenant'
    required: true
  orchestratorApiKey:
    required: false

runs:
  using: "composite"
  steps:
    - run: "C:\\uipathcli\\lib\\net461\\uipcli.exe" package deploy "${{ github.workspace }}" "${{ inputs.orchestratorUrl }}" ${{ inputs.orchestratorTenant }} -u <orchestrator_user> -p <orchestrator_pass> -o ${{ inputs.orchestratorFolderPath }}
      shell: pwsh
