name: 'UiPath Deploy'
description: 'Deploys .nupkg packages in the Github workspace directory to UiPath Orchestrator'

inputs:
  orchestratorUrl: 
    description: 'Orchestrator instance URL'
    required: true
  orchestratorTenant:
    description: 'Tenant on the Orchestrator instance'
    required: true
  orchestratorFolder:
    description: 'Folder path in modern folder setup'
    required: true
  orchestratorApplicationId:
    description: 'Account for authenticating to Orchestrator'
    required: true
  orchestratorApplicationSecret:
    description: 'Password for the Orchestrator account'
    required: true
  orchestratorApplicationScope:
    description: 'Access scope for external application'
    required: true
  orchestratorLogicalName:
    description: 'Logical name for Orchestrator organization'
    required: true

runs:
  using: "composite"
  steps:    
    - name: Deploy
      shell: powershell
      run: uipcli package deploy "${{ github.workspace }}" "${{ inputs.orchestratorUrl }}" ${{ inputs.orchestratorTenant }} --accountForApp "${{ inputs.orchestratorLogicalName }}" --applicationId "${{ inputs.orchestratorApplicationId }}" --applicationSecret "${{ inputs.orchestratorApplicationSecret }}" --applicationScope "${{ inputs.orchestratorApplicationScope }}" --organizationUnit "${{ inputs.orchestratorFolder }}"
