name: 'UiPath Deploy'
description: 'Deploys .nupkg packages in a given directory to UiPath Orchestrator'

inputs:
  orchestratorUrl:
    description: 'URL to Orchestrator instance'
    required: true
  orchestratorFolderPath:
    description: 'The folder path where the process is deployed'
    required: true
  orchestratorTenant: 
    description: 'Name of the Orchestrator Tenant'
    required: true
  orchestratorApiKey:
    required: false
  orchestratorUser:
    description: 'The username of the account deploying the process'
    required: true
secrets:
  orchestratorPassword:
    description: 'Password for the account'
    required: true

runs:
  using: "composite"
  steps:
    - run: "C:\\uipathcli\\lib\\net461\\uipcli.exe" package deploy "${{ github.workspace }}" "${{ inputs.orchestratorUrl }}" ${{ inputs.orchestratorTenant }} -u ${{ inputs.orchestratorUser }} -p ${{ secrets.orchestratorPassword }} -o ${{ inputs.orchestratorFolderPath }}
      shell: pwsh
